Repository SHDS-ESC/StockSimulator-FE, pull requests merged in 2025-09, with the labels that each got.

#3 초기 설정 수정, 테스트 코드 추가
  package-lock.json
  package.json
  src/App.jsx
  src/component/Login.jsx
  src/component/Main.jsx
  src/main.jsx
  src/util/axiosInstance.jsx
  src/util/callToken.jsx
Labels: 세팅

#2 프로젝트 세팅
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  quant-mate/.gitignore
  quant-mate/README.md
  quant-mate/src/App.jsx
  quant-mate/src/index.css
  quant-mate/src/main.jsx
  src/App.css
  src/App.jsx
  src/component/Login.jsx
  src/component/Main.jsx
  src/index.css
  src/main.jsx
  src/util/axiosInstance.jsx
  src/util/callToken.jsx
  vite.config.js
Labels: 세팅

#9 계정 관련 UI
  components.json
  jsconfig.json
  package-lock.json
  package.json
  postcss.config.js
  public/logo.svg
  src/App.jsx
  src/component/Login.jsx
  src/component/Main.jsx
  src/components/Header.jsx
  src/components/page/Login.jsx
  src/components/page/Main.jsx
  src/components/page/Register.jsx
  src/components/ui/badge.jsx
  src/components/ui/button.jsx
  src/components/ui/checkbox.jsx
  src/components/ui/command.jsx
  src/components/ui/dialog.jsx
  src/components/ui/input.jsx
  src/components/ui/label.jsx
  src/components/ui/popover.jsx
  src/components/ui/scroll-area.jsx
  src/components/ui/select.jsx
  src/index.css
  src/lib/utils.js
  src/main.jsx
  src/store/useRegisterStore.jsx
  src/util/axiosInstance.jsx
  src/util/callToken.jsx
  tailwind.config.js
  vite.config.js
Labels: 추가기능, 세팅

#11 마이페이지 기초 세팅
  src/App.jsx
  src/components/Header.jsx
  src/components/page/Main.jsx
  src/components/page/Mypage.jsx
Labels: 추가기능

#8 메인페이지&헤더&푸터 생성
  postcss.config.js
  src/App.css
  src/App.jsx
  src/component/BottomNav.jsx
  src/component/Footer.jsx
  src/component/Header.jsx
  src/component/StockListItem.jsx
  src/hooks/useStockData.jsx
  src/index.css
  src/pages/Character.jsx
  src/pages/HomePage.jsx
  src/pages/News.jsx
  src/pages/Stocks.jsx
  src/util/mockData.jsx
  tailwind.config.js
Labels: 개선, 추가기능

#12 로그인페이지와 병합 후 구조 수정
  src/App.jsx
  src/component/BottomNav.jsx
  src/component/Footer.jsx
  src/component/Header.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/StockListItem.jsx
  src/index.css
  src/pages/Character.jsx
  src/pages/HomePage.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/News.jsx
  src/pages/Register.jsx
  src/pages/Stocks.jsx
Labels: 개선

#28 Feat: 날짜, 턴 종료 로직 추가
  src/components/layout/Layout.jsx
  src/pages/HomePage.jsx
  src/store/useDateStore.jsx
  src/store/useRegisterStore.jsx
Labels: 추가기능

#34 Jiwon/home/simulation
  src/pages/trade/StockLive.jsx
Labels: 개선, 추가기능

#35 9/19 - 시연 전 UX 개선
  src/components/layout/Layout.jsx
  src/index.css
  src/pages/HomePage.jsx
  src/pages/trade/StockLive.jsx
Labels: 개선, 버그, 추가기능

#44 캘린터 날짜 변경, 턴 종료 시 일 별 포트폴리오 생성 기능 구현
  src/App.jsx
  src/components/layout/Layout.jsx
  src/pages/HomePage.jsx
  src/store/useChartStore.jsx
Labels: 개선, 추가기능

#50 유저 일일 포트폴리오 현황 개선
  src/App.jsx
  src/components/layout/Layout.jsx
  src/components/ui/button.jsx
  src/pages/HomePage.jsx
  src/pages/Mypage.jsx
  src/pages/Stocks.jsx
  src/pages/trade/StockLive.jsx
Labels: 개선, 버그, 추가기능

#54 Jiwon/home/simulation
  src/App.jsx
  src/components/layout/Layout.jsx
  src/hooks/useScrollLock.jsx
  src/index.css
  src/pages/BatchBuy.jsx
  src/pages/HomePage.jsx
  src/pages/Stocks.jsx
  src/pages/trade/StockLive.jsx
  src/store/useChartStore.jsx
  src/store/useDateStore.jsx
Labels: 추가기능
